### ISSUE TITLE
Umbraco Extended Distributed Calling plugin requires DescribeEnvironmentResources permission

### ISSUE THREAD

**Issue by arunstephens** [MacmillanCancerSupport/aws#13]
Another required AWS permission is, for example `elasticbeanstalk:DescribeEnvironmentResources on resource: arn:aws:elasticbeanstalk:eu-west-1:ACCOUNT-ID:environment/APPLICATION-NAME/ENVIRONMENT-NAME`.

This is only required for this particular plugin, which we would want to use on all load balanced Umbraco installs.

It's the IAM user that requires this permission. It also needs:

* EC2 describe load balancers
* EC2 describe instances

**Comment by rhysgodfrey** [comment]
@arunstephens Sorry for the really long delay. Looks like this permission has been included for new environments for a while, not sure if this issue was from an environment created before the template was finalized.

The permission is given to the IAM user (the one you login with).

If this is still a problem on an existing project drop me an email and I'll take a look at it's setup.

If you see this issue on a new environment we create for you reopen this issue.
